steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - cafe-search-bot
  - --gen2
  - --region=asia-northeast1
  - --source=.
  - --trigger-http
  - --entry-point=SearchCafe
  - --runtime=go122
  - --allow-unauthenticated
